# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Alana's Blog
tagline:             "Everything is going to be fine."
description:         How do I do this again?
url:                 https://key-puncher.github.io
baseurl:             /
paginate:            5
# google_analytics_id: UA-56228338-1

# About/contact
author:
  name:              Alana Huang
  url:               https://www.linkedin.com/in/alana-y-huang/
  email:             alana.y.huang@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-feed
